In [5]:
import pandas as pd

df=pd.read_csv('State_LA_CSV.csv')


dfIndex=0
dfSize=len(df)

In [3]:
while dfIndex<dfSize:
    
    newST=""
    currST=df.at[dfIndex,'ST_NAME']
    if type(currST)is not str:
        currST=str(currST)
    for ch1 in currST:
        if ch1!='"':
            newST+=ch1
    df.at[dfIndex,'ST_NAME']=newST
    
    
    newDist=""
    currDist=df.at[dfIndex,'DIST_NAME']
    if type(currDist)is not str:
        currDist=str(currDist) 
    for ch2 in currDist:
        if ch2!='"':
            newDist+=ch2
    df.at[dfIndex,'DIST_NAME']=newDist
    
    
    newPC=""
    currPC=df.at[dfIndex,'PC_NAME']
    if type(currPC)is not str:
        currPC=str(currPC)
    for ch3 in currPC:
        if ch3!='"':
            newPC+=ch3
    df.at[dfIndex,'PC_NAME']=newPC
    
    
    newAC=""
    currAC=df.at[dfIndex,'AC_NAME']
    if type(currAC)is not str:
        currAC=str(currAC)
    for ch4 in currAC:
        if ch4!='"':
            newAC+=ch4
    df.at[dfIndex,'AC_NAME']=newAC
    
    dfIndex+=1
print(df['ST_NAME'],df['DIST_NAME'],df['AC_NAME'])

In [7]:
def cleaner (colName):
    newName=""
    currName=df.at[dfIndex,colName]
    if type(currName) is not str:
        currName=str(currName)
    for ch in currName:
        if ch!='"':
            newName+=ch
    return newName

while dfIndex<dfSize:
    df.at[dfIndex,'ST_NAME']=cleaner('ST_NAME')
    df.at[dfIndex,'DIST_NAME']=cleaner('DIST_NAME')
    df.at[dfIndex,'PC_NAME']=cleaner('PC_NAME')
    df.at[dfIndex,'AC_NAME']=cleaner('AC_NAME')
    dfIndex+=1
print(df['ST_NAME'],df['DIST_NAME'],df['PC_NAME'],df['AC_NAME'])

0            GOA
1            GOA
2            GOA
3            GOA
4            GOA
5            GOA
6            GOA
7            GOA
8            GOA
9            GOA
10           GOA
11           GOA
12           GOA
13           GOA
14           GOA
15           GOA
16           GOA
17           GOA
18           GOA
19           GOA
20           GOA
21           GOA
22           GOA
23           GOA
24           GOA
25           GOA
26           GOA
27           GOA
28           GOA
29           GOA
          ...
47003    TRIPURA
47004    TRIPURA
47005    TRIPURA
47006    TRIPURA
47007    TRIPURA
47008    TRIPURA
47009    TRIPURA
47010    TRIPURA
47011    TRIPURA
47012    TRIPURA
47013    TRIPURA
47014    TRIPURA
47015    TRIPURA
47016    TRIPURA
47017    TRIPURA
47018    TRIPURA
47019    TRIPURA
47020    TRIPURA
47021    TRIPURA
47022    TRIPURA
47023    TRIPURA
47024    TRIPURA
47025    TRIPURA
47026    TRIPURA
47027    TRIPURA
47028    TRIPURA
47029    TRIPURA
47030    TRIPURA
47031    TRIPURA
47032    TRIPURA
Name: ST_NAME, Length: 47033, dtype: object 0            NORTH GOA
1            NORTH GOA
2            NORTH GOA
3            NORTH GOA
4            NORTH GOA
5            NORTH GOA
6            NORTH GOA
7            NORTH GOA
8            NORTH GOA
9            NORTH GOA
10           NORTH GOA
11           NORTH GOA
12           NORTH GOA
13           NORTH GOA
14           NORTH GOA
15           NORTH GOA
16           NORTH GOA
17           NORTH GOA
18           NORTH GOA
19           NORTH GOA
20           NORTH GOA
21           NORTH GOA
22           NORTH GOA
23           NORTH GOA
24           NORTH GOA
25           NORTH GOA
26           NORTH GOA
27           NORTH GOA
28           NORTH GOA
29           NORTH GOA
             ...
47003          UNAKOTI
47004          UNAKOTI
47005    NORTH TRIPURA
47006    NORTH TRIPURA
47007    NORTH TRIPURA
47008    NORTH TRIPURA
47009    NORTH TRIPURA
47010    NORTH TRIPURA
47011    NORTH TRIPURA
47012    NORTH TRIPURA
47013    NORTH TRIPURA
47014    NORTH TRIPURA
47015    NORTH TRIPURA
47016    NORTH TRIPURA
47017    NORTH TRIPURA
47018    NORTH TRIPURA
47019    NORTH TRIPURA
47020    NORTH TRIPURA
47021    NORTH TRIPURA
47022    NORTH TRIPURA
47023    NORTH TRIPURA
47024    NORTH TRIPURA
47025    NORTH TRIPURA
47026    NORTH TRIPURA
47027    NORTH TRIPURA
47028    NORTH TRIPURA
47029    NORTH TRIPURA
47030    NORTH TRIPURA
47031    NORTH TRIPURA
47032    NORTH TRIPURA
Name: DIST_NAME, Length: 47033, dtype: object 0           NORTH GOA
1           NORTH GOA
2           NORTH GOA
3           NORTH GOA
4           NORTH GOA
5           NORTH GOA
6           NORTH GOA
7           NORTH GOA
8           NORTH GOA
9           NORTH GOA
10          NORTH GOA
11          NORTH GOA
12          NORTH GOA
13          NORTH GOA
14          NORTH GOA
15          NORTH GOA
16          NORTH GOA
17          NORTH GOA
18          NORTH GOA
19          NORTH GOA
20          NORTH GOA
21          NORTH GOA
22          NORTH GOA
23          NORTH GOA
24          NORTH GOA
25          NORTH GOA
26          NORTH GOA
27          NORTH GOA
28          NORTH GOA
29          NORTH GOA
             ...
47003    TRIPURA EAST
47004    TRIPURA EAST
47005    TRIPURA EAST
47006    TRIPURA EAST
47007    TRIPURA EAST
47008    TRIPURA EAST
47009    TRIPURA EAST
47010    TRIPURA EAST
47011    TRIPURA EAST
47012    TRIPURA EAST
47013    TRIPURA EAST
47014    TRIPURA EAST
47015    TRIPURA EAST
47016    TRIPURA EAST
47017    TRIPURA EAST
47018    TRIPURA EAST
47019    TRIPURA EAST
47020    TRIPURA EAST
47021    TRIPURA EAST
47022    TRIPURA EAST
47023    TRIPURA EAST
47024    TRIPURA EAST
47025    TRIPURA EAST
47026    TRIPURA EAST
47027    TRIPURA EAST
47028    TRIPURA EAST
47029    TRIPURA EAST
47030    TRIPURA EAST
47031    TRIPURA EAST
47032    TRIPURA EAST
Name: PC_NAME, Length: 47033, dtype: object 0                MANDREM
1                MANDREM
2                MANDREM
3                MANDREM
4                MANDREM
5                MANDREM
6                MANDREM
7                MANDREM
8                 PERNEM
9                 PERNEM
10                PERNEM
11                PERNEM
12                PERNEM
13                PERNEM
14                PERNEM
15                PERNEM
16                PERNEM
17              BICHOLIM
18              BICHOLIM
19              BICHOLIM
20              BICHOLIM
21              BICHOLIM
22              BICHOLIM
23                 TIVIM
24                 TIVIM
25                 TIVIM
26                 TIVIM
27                 TIVIM
28                MAPUSA
29                MAPUSA
              ...
47003        KAILASHAHAR
47004        KAILASHAHAR
47005    KADAMTALA KURTI
47006    KADAMTALA KURTI
47007    KADAMTALA KURTI
47008    KADAMTALA KURTI
47009    KADAMTALA KURTI
47010           BAGBASSA
47011           BAGBASSA
47012           BAGBASSA
47013           BAGBASSA
47014        DHARMANAGAR
47015        DHARMANAGAR
47016        DHARMANAGAR
47017        DHARMANAGAR
47018        DHARMANAGAR
47019        DHARMANAGAR
47020       JUBARAJNAGAR
47021       JUBARAJNAGAR
47022       JUBARAJNAGAR
47023          PANISAGAR
47024          PANISAGAR
47025          PANISAGAR
47026          PANISAGAR
47027        PENCHARTHAL
47028        PENCHARTHAL
47029        PENCHARTHAL
47030         KANCHANPUR
47031         KANCHANPUR
47032         KANCHANPUR
Name: AC_NAME, Length: 47033, dtype: object